import { redirect } from 'next/navigation'

// FusionClaw is self-hosted — there's no signup. The owner is the person who
// installs it. Employees come in via invite links generated by the admin.
// Anyone hitting /signup gets sent to /login.
export default function SignupPage() {
  redirect('/login')
}
